spring.application.name=ms-av-01
server.port=8080
servicos.url=http://localhost:8080
spring.datasource.url=jdbc:h2:mem:playyourlist
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
