spring.application.name=ms-av-01
server.port=${PORT:8080}
spring.datasource.url=jdbc:h2:mem:playyourlist;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
servicos.url=${SERVICOS_URL:http://localhost:${server.port}}
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=5000
